#!/usr/bin/env bash
set -e

echo "Starting app..."

docker compose up -d --build

echo "App is starting."
echo "[+] App Should Be Live At ->  http://localhost:8000"
echo
echo "To view logs:"
echo "  docker compose logs -f"