# Generated by Django 5.2.12 on 2026-04-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_seed_initial_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
