# Generated by Django 5.2.12 on 2026-04-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('judge', 'Judge'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
