# Generated by Django 5.2.12 on 2026-04-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
