# Generated by Django 5.2.12 on 2026-04-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_email_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('judge', 'Judge'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
